version: "3.9"
services:
  graphql-engine:
    image: hasura/graphql-engine:v2.44.0
    ports:
      - "${HASURA_PORT:-8080}:8080"
    restart: always
    environment:
      ## Переменные окружения для подключения к базе данных
      HASURA_GRAPHQL_METADATA_DATABASE_URL: ${METADATA_DATABASE_URL}
      PG_DATABASE_URL: ${DATABASE_URL}
      ## Консоль Hasura
      HASURA_GRAPHQL_ENABLE_CONSOLE: ${ENABLE_CONSOLE:-true}
      HASURA_GRAPHQL_DEV_MODE: ${DEV_MODE:-true}
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      ## Секретный ключ администратора
      HASURA_GRAPHQL_ADMIN_SECRET: ${HASURA_ADMIN_SECRET}
  data-connector-agent:
    image: hasura/graphql-data-connector:v2.44.0
    restart: always
    ports:
      - "${DATA_CONNECTOR_PORT:-8081}:8081"
    environment:
      QUARKUS_LOG_LEVEL: ERROR
      QUARKUS_OPENTELEMETRY_ENABLED: "false"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/api/v1/athena/health"]
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 5s
